### ISSUE TITLE
Instantly locks vault upon plugin activation

### ISSUE THREAD

**Issue by leoccyao** [ericbiewener/obsidian-lock-screen-plugin#1]
When plugin is activated after install, the lock screen is instantly shown, before the user has the opportunity to set a password. It is set as the default password (which can be found by looking through the code), and the password can be modified by finding `data.json` in the plugin folder, but these are definitely suboptimal user experiences.

Obsidian v0.13.23, plugin version 1.0.1, Windows 10; tested on a newly created vault.

**Comment by ericbiewener** [comment]
Gross! Fixed in v1.1.0. [Now it defaults to `""` for the password and will show a message saying that you need to configure it](https://github.com/ericbiewener/obsidian-lock-screen-plugin/blob/baf4aa445133c53213517c0d9a89fbd915cbda47/src/show-lock-screen.ts#L11-L32).
