### ISSUE TITLE
'"authorUrl": "https://obsidian.md",' in manifest.json is not your URL

### ISSUE THREAD

**Issue by claremacrae** [ericbiewener/obsidian-lock-screen-plugin#2]
Hi,

I'm just processing all the new plugins in to the Obsidian Hub, and noticed in your manifest.json that the authorUrl in this Plugin is the Obsidian URL, not yours.

**Comment by ericbiewener** [comment]
[Updated.](https://github.com/ericbiewener/obsidian-lock-screen-plugin/blob/1.1.0/manifest.json#L8)

**Comment by claremacrae** [comment]
Super - thanks!
