### ISSUE TITLE
Lock Screen Dismissal Doesn't Focus Workspace When Hidden

### ISSUE THREAD

**Issue by takeo** [ericbiewener/obsidian-lock-screen-plugin#4]
Cool plugin! The only issue I have with it is after putting in the password and dismissing the lock screen I have to click on the workspace in order to start using key commands. Perhaps the `hideLockScreen()` function could focus the workspace or something along those lines? Thanks!

**Comment by ericbiewener** [comment]
Done! Released in v1.3.0.

**Comment by takeo** [comment]
Awesome, thanks! FYI, though, when I try to update/install I get the following error:

`Failed to load resource: the server responded with a status of 404 ()` for `https://github.com/ericbiewener/obsidian-lock-screen-plugin/releases/download/1.3.0/manifest.json`

**Comment by ericbiewener** [comment]
Sorry, try again now. Obsidian's plugin release process is still very manual, so there's plenty of opportunity for human error :)

**Comment by takeo** [comment]
Hell yeah, works perfectly now! Thanks a ton.
